services:
  node:
    build:
      context: images/
      dockerfile: node.Dockerfile
    tty: true
    volumes:
      - .:/workspace:cached
    command: bash
    working_dir: /workspace

  python:
    build:
      context: images/
      dockerfile: python.Dockerfile
    tty: true
    volumes:
      - .:/workspace:cached
    command: bash
    working_dir: /workspace
