name: component-b
# This workflow is the entry-point for all workflows of component b

on:
  # Run on push to main branch
  push:
    branches:
      - main
    paths:
      - "component-b/**"
      - ".github/workflows/component-b-trigger.yaml"
      - '!**/*.md'
  # Run on pull request
  pull_request:
    paths:
      - "component-b/**"
      - ".github/workflows/component-b-trigger.yaml"
      - '!**/*.md'

concurrency:
  # Make sure every job on main has unique group id (run_id), so cancel-in-progress only affects PR's
  # https://stackoverflow.com/questions/74117321/if-condition-in-concurrency-in-gha
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout
  packages: write # for ghcr.io
  # id-token: write # for AWS OIDC

jobs:
  development:
    # Only run on pull request
    if: |
      (github.event_name == 'pull_request' )
    uses: ./.github/workflows/common-deploy.yaml
    secrets: inherit
    with:
      ci_path: ./component-b
      ci_environment: development-env
      ci_image: ghcr.io/${{ github.repository }}/python:latest

      run_lint: true
      run_test: false
      run_deploy: true

  staging:
    # Only run on push to main branch
    if: |
      (github.event_name == 'push' && github.ref_name == 'main')
    uses: ./.github/workflows/common-deploy.yaml
    secrets: inherit
    with:
      ci_path: ./component-b
      ci_environment: staging-env
      ci_image: ghcr.io/${{ github.repository }}/python:latest

      run_lint: false
      run_test: false
      run_deploy: true

  production:
    # Only run on push to main branch
    if: |
      (github.event_name == 'push' && github.ref_name == 'main')
    needs: [staging]
    uses: ./.github/workflows/common-deploy.yaml
    secrets: inherit
    with:
      ci_path: ./component-b
      ci_environment: production-env
      ci_image: ghcr.io/${{ github.repository }}/python:latest

      run_lint: false
      run_test: false
      run_deploy: true
