name: images-node

on:
  # Run on push to main branch
  push:
    branches:
      - main
    paths:
      - ".github/workflows/common-images.yaml"
      - ".github/workflows/images-node-trigger.yaml"
      - "images/node.Dockerfile"
  # Run on pull request
  pull_request:
    paths:
      - ".github/workflows/common-images.yaml"
      - ".github/workflows/images-node-trigger.yaml"
      - "images/node.Dockerfile"

concurrency:
  # Make sure every job on main has unique group id (run_id), so cancel-in-progress only affects PR's
  # https://stackoverflow.com/questions/74117321/if-condition-in-concurrency-in-gha
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout
  packages: write # for ghcr.io

jobs:
  development:
    # Only run on pull request
    if: |
      (github.event_name == 'pull_request' )
    uses: ./.github/workflows/common-images.yaml
    secrets: inherit
    with:
      image_file: node.Dockerfile
      image_name: node
      image_tag: dev

      run_push: false

  production:
    # Only run on push to main branch
    if: |
      (github.event_name == 'push' && github.ref_name == 'main')
    uses: ./.github/workflows/common-images.yaml
    secrets: inherit
    with:
      image_file: node.Dockerfile
      image_name: node
      image_tag: latest

      run_push: true
